on:
  push:
    branches:
      - main
      - release/*
      - feat/*
      - fix/*
      - perf/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run lint
      run: pnpm lint

    - name: Run unit tests
      run: pnpm test